# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [560]:
import numpy as np

vec = np.array([3, 7, 0, 11])
vec.shape
v1 = np.array([4, 3, 1 ,5])
v2 = np.array([2, 3, 1 ,1])
norm = np.linalg.norm(v1)
print(f"norm v1 {v1} = {norm}")
print(f"norm v1 {v1} - v2 {v2} = {np.linalg.norm(v1 - v2)}")
a = np.array([[2, 1, -1], [1, -1, 1]])
b = np.array([[4, -2, 1], [2, -4, -2]])
c = np.array([[1, 2], [2, 1]])
d = np.array([[3, 4], [4, 3]])
e = np.array([1, 2])
i = np.array([[1, 0], [0, 1]])

print(f"###### Uppgift 10.2.1. ######\n(a) 2A={2 * a}")
print(f"#############################\n(b) B-2A=\n{b - (2 * a)}")
print(f"#############################\n(c) 3C - 2E = \n{(3 * c) - (2 * e)}, inte definierad!")
print(f"#############################\n(d) 2D - 3C = \n{(2 * d) - (3 * c)}")
print(f"#############################\n(e) DT + 2D = \n{(d.T) + (2 * d)}")
print(f"#############################\n(f) 2CT - 2DT = \n{(2 * c.T) - (2 * d.T)}")
try:
    print(f"#############################\n(g) AT - B = \n{(a.T) - (b)}")
except Exception as e:
    print(f"#############################\n(g) Det gick inte AT - B : {e}")
try:
    print(f"#############################\n(h) AC = \n{(a @ c)}")  
except Exception as e:
    print(f"#############################\n(h) Det gick inte AC : {e}")
print(f"#############################\n(i) CD = \n{(c @ d)}") 
print(f"#############################\n(j) CB = \n{(c @ b)}") 
print(f"#############################\n(k) CI = \n{(c @ i)}") 
print(f"#############################\n(l) ABT = \n{(a @ b.T)}") 

A = np.array([[2, 3, 4], [5, 4, 1]])
print(f"###### Uppgift 10.2.2. ######\n AAT= \n{A @ A.T}")

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])
print(f"###### Uppgift 10.2.3. ######\n AB= \n{A @ B}\nAC=\n{A @ C}\n B == C : {B == C}")

A = np.array([[3, 2, 4], [2, 3, 8], [4, 1, 3], [7, 1, 5]])
#x = np.array([x1, x2, x3, x4])
b = np.array([5, -1, 8, 3, -6])

#Exempel 10.32
A = np.array([[2, 3, -1], [4, -1, 2], [1, 2, -3]])
b = np.array([5, -1, 8])
# Lös ekvationssystemet
x = np.linalg.solve(A, b)
print(f"Lösningen 10.32 första 3 ekvationerna, x är:{x}")

check = np.allclose(np.dot(A, x), b)
print("Stämmer lösningen?", check)

ekv4 = np.array([3, -1, 8])
print(f"Sätt in x i ekvationen, ska resultera i b {b} : {A @ x}")
print(f"3x − y + z bör bli 3. Men...= {ekv4.T @ x}")



norm v1 [4 3 1 5] = 7.14142842854285
norm v1 [4 3 1 5] - v2 [2 3 1 1] = 4.47213595499958
###### Uppgift 10.2.1. ######
(a) 2A=[[ 4  2 -2]
 [ 2 -2  2]]
#############################
(b) B-2A=
[[ 0 -4  3]
 [ 0 -2 -4]]
#############################
(c) 3C - 2E = 
[[ 1  2]
 [ 4 -1]], inte definierad!
#############################
(d) 2D - 3C = 
[[3 2]
 [2 3]]
#############################
(e) DT + 2D = 
[[ 9 12]
 [12  9]]
#############################
(f) 2CT - 2DT = 
[[-4 -4]
 [-4 -4]]
#############################
(g) Det gick inte AT - B : operands could not be broadcast together with shapes (3,2) (2,3) 
#############################
(h) Det gick inte AC : matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
#############################
(i) CD = 
[[11 10]
 [10 11]]
#############################
(j) CB = 
[[  8 -10  -3]
 [ 10  -8   0]]
#############################
(k) CI = 
[[1 2]
 [2 1]]
#############

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [561]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)
print(f"############################################\nMatrix:\n{A}\n")
print(f"Dimension is:{A.ndim}, shape is:{A.shape}, size is:{A.size}, Datatype of matrix A is:{A.dtype}")


############################################
Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Dimension is:2, shape is:(3, 5), size is:15, Datatype of matrix A is:int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [562]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
print("B:\n", B)
print("C:\n", C)
print(f"Elementwise subtraction\n{B - C}")
print(f"Elementwise multiplication:\n{B * C}")
print(f"Matrix multiplication:\n{B @ C}")

B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
C:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [563]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
B = np.arange(1, 10).reshape(3, 3)

print(f"""
### Do the following calculations on the matrix:
{B}   
* Exponentiate each number elementwise (use the np.exp function).
{np.exp(B)}
* Calculate the minimum value in the whole matrix. :{np.min(B)}
* Calculcate the minimum value in each row. {np.min(B, axis = 1)}
* Calculcate the minimum value in each column. {np.min(B, axis = 0)}


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin). {np.argmin(B)}
* Find the index value for the minimum value in each row (hint: use np.argmin). {np.argmin(B, axis=1)}


* Calculate the sum for all elements. {np.sum(B)}
* Calculate the mean for each column. {np.mean(B , axis=1)}
* Calculate the median for each column. {np.median(B , axis=1)}
""")


### Do the following calculations on the matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]   
* Exponentiate each number elementwise (use the np.exp function).
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
* Calculate the minimum value in the whole matrix. :1
* Calculcate the minimum value in each row. [1 4 7]
* Calculcate the minimum value in each column. [1 2 3]


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin). 0
* Find the index value for the minimum value in each row (hint: use np.argmin). [0 0 0]


* Calculate the sum for all elements. 45
* Calculate the mean for each column. [2. 5. 8.]
* Calculate the median for each column. [2. 5. 8.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [564]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [565]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [14]:
### What does it mean when you provide fewer indices than axes when slicing? See example below.
print(f"#############################\nA\n{A}")
print(f"#############################\nA[1]\n{A[1]}")
print(f"#############################\nA[1, :]\n{A[1, :]}")
print(f"#############################\nA[:2,1:3]\n{A[:2,1:3]}")
print(f"#############################\nA[2]\n{A[2]}")
print("""ANSWER: 
      If you provide fewer axes then only the axes specified are used.
      The missing axes are terated as a complete slice ':'
      If you specify the slice it is applied.
      """)

#############################
A
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
#############################
A[1]
[ 6  7  8  9 10]
#############################
A[1, :]
[ 6  7  8  9 10]
#############################
A[:2,1:3]
[[2 3]
 [7 8]]
#############################
A[2]
[11 12 13 14 15]
ANSWER: 
      If you provide fewer axes then only the axes specified is used.
      The missing axes are terated as a complete slice ':'
      If you specify the slice it is applied.
      


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [566]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [567]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [20]:
print("iterate through the array *elementwise*. Use '.flat':")
for i in A.flat:
    print(i)

iterate through the array *elementwise*. Use '.flat':
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [568]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [22]:
a = np.arange(30) ### Create a one dimensional array
b = a.reshape((2, 3, -1)) ## 2 : size of first axes, 3 : Size of second axis, -1 calculate size of remaining axes (30 / (2*3) == 5)
print(a)
print()

print(b)
print(f"Array b has {b.ndim} dimensions with the sahpe {b.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Array b has 3 dimensions with the sahpe (2, 3, 5)


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [569]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [570]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [571]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [26]:
def add_mult_matrices(matrix1, matrix2, operation : str):
    """
    Perform addition or multiplication of two matrices.
    
    Args:
        matrix1 (numpy.ndarray): The first matrix.
        matrix2 (numpy.ndarray): The second matrix.
        operation (str): Either 'add' or 'multiply', specifying the operation.
    
    Returns:
        numpy.ndarray: Result of the operation (addition or multiplication).
    
    Raises:
        TypeError: If inputs are not of type numpy.ndarray.
        ValueError: If operation is not 'add' or 'multiply'.
        ValueError: If matrices have incompatible sizes for the operation.
    """
    # Validate input types
    op = operation.lower()
    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise TypeError("Both inputs must be of type numpy.ndarray")
    
    # Validate the operation
    if op not in {'add', 'multiply'}:
        raise ValueError("The operation must be either 'add' or 'multiply'")
    
    # Perform addition
    if op == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("For addition, matrices must have the same size")
        return matrix1 + matrix2
    
    # Perform multiplication
    if op == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("For multiplication, number of columns in the first matrix must equal the number of rows in the second matrix")
        # return np.dot(matrix1, matrix2)
        return matrix1 @ matrix2

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(f"#############################\nAdd:\n{add_mult_matrices(matrix1, matrix2, 'add')}")
print(f"#############################\nMultiply:\n{add_mult_matrices(matrix1, matrix2, 'multiply')}")

#############################
Add:
[[ 6  8]
 [10 12]]
#############################
Multiply:
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [30]:
import numpy as np

x = np.array([4, 3])
print(f"#############################\n10.1.1\n(a) Dimension: {x.shape} dimensionen är 1 x 2")
print(f"#############################\n(b) 5x: {x * 5}")
print(f"#############################\n(c) 3x: {3 * x }")
print(f"#############################\n(d) 5x + 3x: {(5 * x) + (3 * x)}")
print(f"#############################\n(e) 8x: {8 * x }")
print(f"#############################\n(f) 4x - x: {(4 * x) - x}")
print(f"#############################\n(g) x: {x}\n xT: { x.T } dimension {x.T.shape} dimensionen är 2 x 1")
print(f"#############################\n(h) x: + + xT: { x + x.T }")
print(f"#############################\n(i) Normen av x: {np.linalg.norm(x)}")

v = np.array([[3], [7], [0], [11]])
print(f"#############################\n10.1.2\n(a) Dimension: {x.shape} dimensionen är 4 x 1")
print(f"#############################\n(b) 2v:\n {2 * v}")
print(f"#############################\n(c) 5v + 2v:\n {(5 * v) + (2 * v)}")
print(f"#############################\n(c) 7v:\n {(7 * v)}")
print(f"#############################\n(d) 4v - 2v:\n {(4 * v) - (2 * v)}")
print(f"#############################\n(d) 4v - 2v = 2v:\n {(2 * v)}")
print(f"#############################\n(e) vT:\n {(v.T)} dimensionen är {(v.T.shape)}")
print(f"#############################\n(f) Normen av v: {np.linalg.norm(v)}")

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
print(f"#############################\n10.1.3\n(a) Normen av v1: {np.linalg.norm(v1)}")
print(f"#############################\n(b) Normen av v1 - v2: {np.linalg.norm(v1 - v2)}")




#############################
10.1.1
(a) Dimension: (2,) dimensionen är 1 x 2
#############################
(b) 5x: [20 15]
#############################
(c) 3x: [12  9]
#############################
(d) 5x + 3x: [32 24]
#############################
(e) 8x: [32 24]
#############################
(f) 4x - x: [12  9]
#############################
(g) x: [4 3]
 xT: [4 3] dimension (2,) dimensionen är 2 x 1
#############################
(h) x: + + xT: [8 6]
#############################
(i) Normen av x: 5.0
#############################
10.1.2
(a) Dimension: (2,) dimensionen är 4 x 1
#############################
(b) 2v:
 [[ 6]
 [14]
 [ 0]
 [22]]
#############################
(c) 5v + 2v:
 [[21]
 [49]
 [ 0]
 [77]]
#############################
(c) 7v:
 [[21]
 [49]
 [ 0]
 [77]]
#############################
(d) 4v - 2v:
 [[ 6]
 [14]
 [ 0]
 [22]]
#############################
(d) 4v - 2v = 2v:
 [[ 6]
 [14]
 [ 0]
 [22]]
#############################
(e) vT:
 [[ 3  7  0 11]] dimensionen är (1,

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [28]:
import numpy as np

vec = np.array([3, 7, 0, 11])
vec.shape
v1 = np.array([4, 3, 1 ,5])
v2 = np.array([2, 3, 1 ,1])
norm = np.linalg.norm(v1)
print(f"norm v1 {v1} = {norm}")
print(f"norm v1 {v1} - v2 {v2} = {np.linalg.norm(v1 - v2)}")
a = np.array([[2, 1, -1], [1, -1, 1]])
b = np.array([[4, -2, 1], [2, -4, -2]])
c = np.array([[1, 2], [2, 1]])
d = np.array([[3, 4], [4, 3]])
e = np.array([1, 2])
i = np.array([[1, 0], [0, 1]])

print(f"###### Uppgift 10.2.1. ######\n(a) 2A={2 * a}")
print(f"#############################\n(b) B-2A=\n{b - (2 * a)}")
print(f"#############################\n(c) 3C - 2E = \n{(3 * c) - (2 * e)}, inte definierad!")
print(f"#############################\n(d) 2D - 3C = \n{(2 * d) - (3 * c)}")
print(f"#############################\n(e) DT + 2D = \n{(d.T) + (2 * d)}")
print(f"#############################\n(f) 2CT - 2DT = \n{(2 * c.T) - (2 * d.T)}")
try:
    print(f"#############################\n(g) AT - B = \n{(a.T) - (b)}")
except Exception as e:
    print(f"#############################\n(g) Det gick inte AT - B : {e}")
try:
    print(f"#############################\n(h) AC = \n{(a @ c)}")  
except Exception as e:
    print(f"#############################\n(h) Det gick inte AC : {e}")
print(f"#############################\n(i) CD = \n{(c @ d)}") 
print(f"#############################\n(j) CB = \n{(c @ b)}") 
print(f"#############################\n(k) CI = \n{(c @ i)}") 
print(f"#############################\n(l) ABT = \n{(a @ b.T)}") 

A = np.array([[2, 3, 4], [5, 4, 1]])
print(f"###### Uppgift 10.2.2. ######\n AAT= \n{A @ A.T}")

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])
print(f"###### Uppgift 10.2.3. ######\n AB= \n{A @ B}\nAC=\n{A @ C}\n B == C : {B == C}")

A = np.array([[3, 2, 4], [2, 3, 8], [4, 1, 3], [7, 1, 5]])
#x = np.array([x1, x2, x3, x4])
b = np.array([5, -1, 8, 3, -6])

#Exempel 10.32
A = np.array([[2, 3, -1], [4, -1, 2], [1, 2, -3]])
b = np.array([5, -1, 8])
# Lös ekvationssystemet
x = np.linalg.solve(A, b)
print(f"Lösningen 10.32 första 3 ekvationerna, x är:{x}")

check = np.allclose(np.dot(A, x), b)
print("Stämmer lösningen?", check)

ekv4 = np.array([3, -1, 8])
print(f"Sätt in x i ekvationen, ska resultera i b {b} : {A @ x}")
print(f"3x − y + z bör bli 3. Men...= {ekv4.T @ x}")



norm v1 [4 3 1 5] = 7.14142842854285
norm v1 [4 3 1 5] - v2 [2 3 1 1] = 4.47213595499958
###### Uppgift 10.2.1. ######
(a) 2A=[[ 4  2 -2]
 [ 2 -2  2]]
#############################
(b) B-2A=
[[ 0 -4  3]
 [ 0 -2 -4]]
#############################
(c) 3C - 2E = 
[[ 1  2]
 [ 4 -1]], inte definierad!
#############################
(d) 2D - 3C = 
[[3 2]
 [2 3]]
#############################
(e) DT + 2D = 
[[ 9 12]
 [12  9]]
#############################
(f) 2CT - 2DT = 
[[-4 -4]
 [-4 -4]]
#############################
(g) Det gick inte AT - B : operands could not be broadcast together with shapes (3,2) (2,3) 
#############################
(h) Det gick inte AC : matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
#############################
(i) CD = 
[[11 10]
 [10 11]]
#############################
(j) CB = 
[[  8 -10  -3]
 [ 10  -8   0]]
#############################
(k) CI = 
[[1 2]
 [2 1]]
#############

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [34]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)
v2[-1] = 666
print(v1)
print("Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?")
print("Svar: v2 is a view since v2 is created a subset of v1. So it will be changed")

[0 1 2 3]
[2 3]
[  0   1   2 666]
Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?
Svar: v2 is a view since v2 is created a subset of v1. So it will be changed


In [573]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [574]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
